name: rpg_game
services:
  db:
    container_name: rpg-game-db
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5200:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgres
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 5050:8080

volumes:
    db-data:
      name: ${DATABASE_VOLUME}
      driver: local
